Add STAC as a checkout option
planetlabs/qgis-planet-plugin pull request #67
Opened 2022-11-07 21:10 UTC by Samweli

These changes enabled using STAC metadata as an option when making orders.

The current behaviour is user enable the STAC metadata option by clicking `STAC` button and can disable it by re-clicking the same button.
This behaviour is per delivered from the below mockup 
![image](https://user-images.githubusercontent.com/2663775/200415012-7f28e571-29e1-43b8-94f3-dcbb659445df.png)

Although this achieves the intended outcome, I'm advising to use a checkbox instead of a button and will make the change if this change is confirmed.

Screenshot
![stac_checkout_option](https://user-images.githubusercontent.com/2663775/200415639-7b062024-e19a-4909-8669-887ba16b922a.gif)

2022-11-16 17:07 UTC, john-dupuy commented
@Samweli can you add a test for this new feature?

2022-11-16 17:10 UTC, john-dupuy commented on planet_explorer/gui/pe_orders.py
> +            self.btnSTAC.setStyleSheet(
Can we put the style sheets in the `.ui` file?

2022-11-16 17:11 UTC, john-dupuy commented on planet_explorer/gui/pe_orders.py
> +            self.btnSTAC.setStyleSheet(
Same comment here about the style sheet.

2022-11-16 17:11 UTC, john-dupuy requested changes
Couple of small questions about the style sheet and adding a test case. Otherwise LGTM

2023-01-02 19:18 UTC, astrong19 commented
Hey! I had some UI design feedback on the STAC metadata tool. 

1.) Could we use the same font and style as the Harmonization and Clip tools... for example, can we **Bold** METADATA 
<img width="588" alt="STAC feedback" src="https://user-images.githubusercontent.com/8313799/210271130-cf2edd20-87fc-4953-a605-cb0221e6dd92.PNG">

2023-01-31 13:09 UTC, Samweli commented
@astrong19 The latest commit contain UI updates you have requested on the past comment, see below the new look of the Order dialog

![image](https://user-images.githubusercontent.com/2663775/215768409-03c3db4c-59e6-43b9-84c6-f5c9a94a1846.png)

2023-01-31 23:38 UTC, john-dupuy commented
OK so I tested this locally and can confirm it's working - I just want to confirm the UI. On Linux:

**Ordering STAC metadata**
![Screenshot from 2023-01-31 15-34-48](https://user-images.githubusercontent.com/44065123/215908112-e881d2a4-3ec4-4044-b5ae-c2a505237e3a.png)


**Not Ordering STAC metadata**
![Screenshot from 2023-01-31 15-35-45](https://user-images.githubusercontent.com/44065123/215908151-843572df-bc45-426d-8d49-ca7aa7e72344.png)


IMO they should be flipped, i.e. the filled button should be for when you _are_ getting STAC metadata.

2023-01-31 23:59 UTC, john-dupuy commented
> OK so I tested this locally and can confirm it's working - I just want to confirm the UI. On Linux:
> 
> 
> IMO they should be flipped, i.e. the filled button should be for when you _are_ getting STAC metadata.

Looking at the code and I see that this is the intention - however, I think there is a bug where the order dialog "remembers" what the previous selected option was. So if you go through and order an item with STAC enabled once, it will enabled the next time you order that item, regardless of the button's styling. 

We should reset this button when the order dialog is opened. FYI @astrong19

2023-02-01 00:06 UTC, john-dupuy commented on planet_explorer/gui/pe_orders.py
> +        self.stac_order = QSettings().value(
I think here we also need to reset the CSS of the button.

2023-02-01 11:46 UTC, Samweli commented
> We should reset this button style when the order dialog is opened. FYI @astrong19 @Samweli


> however, I think there is a bug where the order dialog "remembers"

@john-dupuy It is not bug, that how I designed it to work that once user select/un-select the STAC Metadata option then the plugin should always remember that selection so they don't have to click the option each time they open the Order dialog.

We can change it if you and @astrong19 agree that we should change the workflow, but in my opinion it is usually better to save user defined options so they won't have to reselect them each time.

2023-02-01 15:21 UTC, john-dupuy commented
> > We should reset this button style when the order dialog is opened. FYI @astrong19 @Samweli
> 
> > however, I think there is a bug where the order dialog "remembers"
> 
> @john-dupuy It is not bug, that how I designed it to work that once user select/un-select the STAC Metadata option then the plugin should always remember that selection so they don't have to click the option each time they open the Order dialog.
> 
> We can change it if you and @astrong19 agree that we should change the workflow, but in my opinion it is usually better to save user defined options so they won't have to reselect them each time.

The issue is not really the "remembering" but rather the fact that the disabled/enabled styling for the button can become flipped. So the user will press the button and think they've selected STAC metadata to be delivered, but the order will not contain any STAC metadata.

2023-02-01 18:51 UTC, Samweli commented
> @Samweli The issue is not really the "remembering" but rather the fact that the disabled/enabled styling for the button can become flipped

Right @john-dupuy, I ll remove the "remembering" logic that should resolve the issue. Do you think we should use a normal checkbox like in the other options, I do realize that this can be against the shared UI for this feature but all the other options just use a checkbox.

2023-02-01 19:14 UTC, john-dupuy commented
> > @Samweli The issue is not really the "remembering" but rather the fact that the disabled/enabled styling for the button can become flipped
> 
> Right @john-dupuy, I ll remove the "remembering" logic that should resolve the issue. Do you think we should use a normal checkbox like in the other options, I do realize that this can be against the shared UI for this feature but all the other options just use a checkbox.

@Samweli afaik @astrong19 would like to keep the button as is - I say we remove the remembering logic and revisit making it a check box after the fact.

2023-02-02 14:20 UTC, astrong19 commented
Talking to the team a bit today I think we should actually change the UI for the STAC metadata checkout to a checkbox so that it's more consistent and less confusing. Also we can add an option to the plugin settings to enable STAC by default. The text can be "Enable STAC metadata by default"
<img width="319" alt="settings" src="https://user-images.githubusercontent.com/8313799/216349494-13becf53-7280-4aba-84d3-af63369ba10c.PNG">

2023-02-02 14:54 UTC, Samweli commented
> Talking to the team a bit today I think we should actually change the UI for the STAC metadata checkout to a checkbox so that it's more consistent and less confusing. Also we can add an option to the plugin settings to enable STAC by default. The text can be "Enable STAC metadata by default"

Right @astrong19, working on adding this to the current PR.

2023-02-02 17:32 UTC, john-dupuy approved these changes
Thanks @Samweli - tested locally and the checkbox is working.

2023-02-02 17:43 UTC, Samweli commented
> Thanks @Samweli - tested locally and the checkbox is working.

Alright @john-dupuy, I have also updated the settings dialog to include the STAC metadata tool option, see below
![Workspace 1_005](https://user-images.githubusercontent.com/2663775/216401177-78ff4689-01f7-4ad1-a49b-39838fd8360d.png)

2023-02-02 18:07 UTC, merged

2023-02-03 14:17 UTC, astrong19 commented
Looks good to me, thanks!